tasks:
  - command: npm i -g live-server && gp sync-done live-server
  - command: gp sync-await live-server && live-server .
  - command: gp sync-await live-server && live-server --port=8081 .
  - command: gp sync-await live-server && live-server --port=8082 .
  - command: gp sync-await live-server && live-server --port=8083 .
 
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  - port: 8081
    onOpen: notify
    visibility: public
  - port: 8082
    onOpen: ignore
  - port: 8083
    onOpen: notify
